// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fuota/fuota.proto

package fuota

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MulticastGroupType int32

const (
	// Class-B.
	MulticastGroupType_CLASS_B MulticastGroupType = 0
	// Class-C.
	MulticastGroupType_CLASS_C MulticastGroupType = 1
)

var MulticastGroupType_name = map[int32]string{
	0: "CLASS_B",
	1: "CLASS_C",
}

var MulticastGroupType_value = map[string]int32{
	"CLASS_B": 0,
	"CLASS_C": 1,
}

func (x MulticastGroupType) String() string {
	return proto.EnumName(MulticastGroupType_name, int32(x))
}

func (MulticastGroupType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{0}
}

type RequestFragmentationSessionStatus int32

const (
	// Enqueue the fragmentation-session status request command directly after
	// enqueueing the fragmentation-session fragments. This is the recommended
	// option for Class-A devices as the status request will stay in the
	// downlink queue until the device sends its next uplink.
	RequestFragmentationSessionStatus_AFTER_FRAGMENT_ENQUEUE RequestFragmentationSessionStatus = 0
	// Enqueue the fragmentation-session status request after the multicast
	// session-timeout. This is the recommended option for Class-B and -C
	// devices as selecting AFTER_FRAGMENT_ENQUEUE will likely cause the NS
	// to schedule the downlink frame during the FUOTA multicast-session.
	RequestFragmentationSessionStatus_AFTER_SESSION_TIMEOUT RequestFragmentationSessionStatus = 1
	// Do not request the fragmentation-session status.
	RequestFragmentationSessionStatus_NO_REQUEST RequestFragmentationSessionStatus = 2
)

var RequestFragmentationSessionStatus_name = map[int32]string{
	0: "AFTER_FRAGMENT_ENQUEUE",
	1: "AFTER_SESSION_TIMEOUT",
	2: "NO_REQUEST",
}

var RequestFragmentationSessionStatus_value = map[string]int32{
	"AFTER_FRAGMENT_ENQUEUE": 0,
	"AFTER_SESSION_TIMEOUT":  1,
	"NO_REQUEST":             2,
}

func (x RequestFragmentationSessionStatus) String() string {
	return proto.EnumName(RequestFragmentationSessionStatus_name, int32(x))
}

func (RequestFragmentationSessionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{1}
}

type DeploymentDevice struct {
	// DevEUI.
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// McRootKey.
	McRootKey            []byte   `protobuf:"bytes,2,opt,name=mc_root_key,json=mcRootKey,proto3" json:"mc_root_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeploymentDevice) Reset()         { *m = DeploymentDevice{} }
func (m *DeploymentDevice) String() string { return proto.CompactTextString(m) }
func (*DeploymentDevice) ProtoMessage()    {}
func (*DeploymentDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{0}
}

func (m *DeploymentDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentDevice.Unmarshal(m, b)
}
func (m *DeploymentDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentDevice.Marshal(b, m, deterministic)
}
func (m *DeploymentDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentDevice.Merge(m, src)
}
func (m *DeploymentDevice) XXX_Size() int {
	return xxx_messageInfo_DeploymentDevice.Size(m)
}
func (m *DeploymentDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentDevice.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentDevice proto.InternalMessageInfo

func (m *DeploymentDevice) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *DeploymentDevice) GetMcRootKey() []byte {
	if m != nil {
		return m.McRootKey
	}
	return nil
}

type BulkDeploymentDevice struct {
	// DevEUI.
	DevEui               string   `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkDeploymentDevice) Reset()         { *m = BulkDeploymentDevice{} }
func (m *BulkDeploymentDevice) String() string { return proto.CompactTextString(m) }
func (*BulkDeploymentDevice) ProtoMessage()    {}
func (*BulkDeploymentDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{1}
}

func (m *BulkDeploymentDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkDeploymentDevice.Unmarshal(m, b)
}
func (m *BulkDeploymentDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkDeploymentDevice.Marshal(b, m, deterministic)
}
func (m *BulkDeploymentDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkDeploymentDevice.Merge(m, src)
}
func (m *BulkDeploymentDevice) XXX_Size() int {
	return xxx_messageInfo_BulkDeploymentDevice.Size(m)
}
func (m *BulkDeploymentDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkDeploymentDevice.DiscardUnknown(m)
}

var xxx_messageInfo_BulkDeploymentDevice proto.InternalMessageInfo

func (m *BulkDeploymentDevice) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

type Deployment struct {
	// Application ID.
	ApplicationId int64 `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// Devices to include in this deployment.
	Devices []*DeploymentDevice `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	// Multicast-group type.
	MulticastGroupType MulticastGroupType `protobuf:"varint,3,opt,name=multicast_group_type,json=multicastGroupType,proto3,enum=fuota.MulticastGroupType" json:"multicast_group_type,omitempty"`
	// Multicast data-rate.
	MulticastDr uint32 `protobuf:"varint,4,opt,name=multicast_dr,json=multicastDr,proto3" json:"multicast_dr,omitempty"`
	// Multicast ping-slot period (Class-B only).
	MulticastPingSlotPeriod uint32 `protobuf:"varint,5,opt,name=multicast_ping_slot_period,json=multicastPingSlotPeriod,proto3" json:"multicast_ping_slot_period,omitempty"`
	// Multicast frequency (Hz).
	MulticastFrequency uint32 `protobuf:"varint,6,opt,name=multicast_frequency,json=multicastFrequency,proto3" json:"multicast_frequency,omitempty"`
	// Multicast group ID.
	MulticastGroupId uint32 `protobuf:"varint,7,opt,name=multicast_group_id,json=multicastGroupId,proto3" json:"multicast_group_id,omitempty"`
	// Multicast timeout.
	// This defines the timeout of the multicast-session.
	// Please refer to the Remote Multicast Setup specification as this field
	// has a different meaning for Class-B and Class-C groups.
	MulticastTimeout uint32 `protobuf:"varint,8,opt,name=multicast_timeout,json=multicastTimeout,proto3" json:"multicast_timeout,omitempty"`
	// Unicast timeout.
	// Set this to the value in which you at least expect an uplink frame from
	// the device. The FUOTA server will wait for the given time before
	// attempting a retry or continuing with the next step.
	UnicastTimeout *duration.Duration `protobuf:"bytes,9,opt,name=unicast_timeout,json=unicastTimeout,proto3" json:"unicast_timeout,omitempty"`
	// Unicast attempt count.
	// The number of attempts before considering an unicast command
	// to be failed.
	UnicastAttemptCount uint32 `protobuf:"varint,10,opt,name=unicast_attempt_count,json=unicastAttemptCount,proto3" json:"unicast_attempt_count,omitempty"`
	// FragmentationFragmentSize.
	// This defines the size of each payload fragment. Please refer to the
	// Regional Parameters specification for the maximum payload sizes
	// per data-rate and region.
	FragmentationFragmentSize uint32 `protobuf:"varint,11,opt,name=fragmentation_fragment_size,json=fragmentationFragmentSize,proto3" json:"fragmentation_fragment_size,omitempty"`
	// Payload.
	Payload []byte `protobuf:"bytes,12,opt,name=payload,proto3" json:"payload,omitempty"`
	// Fragmentation redundancy.
	// The number represents the additional redundant frames to send.
	FragmentationRedundancy uint32 `protobuf:"varint,13,opt,name=fragmentation_redundancy,json=fragmentationRedundancy,proto3" json:"fragmentation_redundancy,omitempty"`
	// Fragmentation session index.
	FragmentationSessionIndex uint32 `protobuf:"varint,14,opt,name=fragmentation_session_index,json=fragmentationSessionIndex,proto3" json:"fragmentation_session_index,omitempty"`
	// Fragmentation matrix.
	FragmentationMatrix uint32 `protobuf:"varint,15,opt,name=fragmentation_matrix,json=fragmentationMatrix,proto3" json:"fragmentation_matrix,omitempty"`
	// Block ack delay.
	FragmentationBlockAckDelay uint32 `protobuf:"varint,16,opt,name=fragmentation_block_ack_delay,json=fragmentationBlockAckDelay,proto3" json:"fragmentation_block_ack_delay,omitempty"`
	// Descriptor (4 bytes).
	FragmentationDescriptor []byte `protobuf:"bytes,17,opt,name=fragmentation_descriptor,json=fragmentationDescriptor,proto3" json:"fragmentation_descriptor,omitempty"`
	// Request fragmentation session status.
	RequestFragmentationSessionStatus RequestFragmentationSessionStatus `protobuf:"varint,18,opt,name=request_fragmentation_session_status,json=requestFragmentationSessionStatus,proto3,enum=fuota.RequestFragmentationSessionStatus" json:"request_fragmentation_session_status,omitempty"`
	XXX_NoUnkeyedLiteral              struct{}                          `json:"-"`
	XXX_unrecognized                  []byte                            `json:"-"`
	XXX_sizecache                     int32                             `json:"-"`
}

func (m *Deployment) Reset()         { *m = Deployment{} }
func (m *Deployment) String() string { return proto.CompactTextString(m) }
func (*Deployment) ProtoMessage()    {}
func (*Deployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{2}
}

func (m *Deployment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Deployment.Unmarshal(m, b)
}
func (m *Deployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Deployment.Marshal(b, m, deterministic)
}
func (m *Deployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Deployment.Merge(m, src)
}
func (m *Deployment) XXX_Size() int {
	return xxx_messageInfo_Deployment.Size(m)
}
func (m *Deployment) XXX_DiscardUnknown() {
	xxx_messageInfo_Deployment.DiscardUnknown(m)
}

var xxx_messageInfo_Deployment proto.InternalMessageInfo

func (m *Deployment) GetApplicationId() int64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *Deployment) GetDevices() []*DeploymentDevice {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *Deployment) GetMulticastGroupType() MulticastGroupType {
	if m != nil {
		return m.MulticastGroupType
	}
	return MulticastGroupType_CLASS_B
}

func (m *Deployment) GetMulticastDr() uint32 {
	if m != nil {
		return m.MulticastDr
	}
	return 0
}

func (m *Deployment) GetMulticastPingSlotPeriod() uint32 {
	if m != nil {
		return m.MulticastPingSlotPeriod
	}
	return 0
}

func (m *Deployment) GetMulticastFrequency() uint32 {
	if m != nil {
		return m.MulticastFrequency
	}
	return 0
}

func (m *Deployment) GetMulticastGroupId() uint32 {
	if m != nil {
		return m.MulticastGroupId
	}
	return 0
}

func (m *Deployment) GetMulticastTimeout() uint32 {
	if m != nil {
		return m.MulticastTimeout
	}
	return 0
}

func (m *Deployment) GetUnicastTimeout() *duration.Duration {
	if m != nil {
		return m.UnicastTimeout
	}
	return nil
}

func (m *Deployment) GetUnicastAttemptCount() uint32 {
	if m != nil {
		return m.UnicastAttemptCount
	}
	return 0
}

func (m *Deployment) GetFragmentationFragmentSize() uint32 {
	if m != nil {
		return m.FragmentationFragmentSize
	}
	return 0
}

func (m *Deployment) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Deployment) GetFragmentationRedundancy() uint32 {
	if m != nil {
		return m.FragmentationRedundancy
	}
	return 0
}

func (m *Deployment) GetFragmentationSessionIndex() uint32 {
	if m != nil {
		return m.FragmentationSessionIndex
	}
	return 0
}

func (m *Deployment) GetFragmentationMatrix() uint32 {
	if m != nil {
		return m.FragmentationMatrix
	}
	return 0
}

func (m *Deployment) GetFragmentationBlockAckDelay() uint32 {
	if m != nil {
		return m.FragmentationBlockAckDelay
	}
	return 0
}

func (m *Deployment) GetFragmentationDescriptor() []byte {
	if m != nil {
		return m.FragmentationDescriptor
	}
	return nil
}

func (m *Deployment) GetRequestFragmentationSessionStatus() RequestFragmentationSessionStatus {
	if m != nil {
		return m.RequestFragmentationSessionStatus
	}
	return RequestFragmentationSessionStatus_AFTER_FRAGMENT_ENQUEUE
}

type MulticastDeployment struct {
	// Application ID.
	ApplicationId int64 `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// Devices to include in this deployment.
	Devices []*DeploymentDevice `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	// Multicast-group type.
	MulticastGroupType MulticastGroupType `protobuf:"varint,3,opt,name=multicast_group_type,json=multicastGroupType,proto3,enum=fuota.MulticastGroupType" json:"multicast_group_type,omitempty"`
	// Multicast data-rate.
	MulticastDr uint32 `protobuf:"varint,4,opt,name=multicast_dr,json=multicastDr,proto3" json:"multicast_dr,omitempty"`
	// Multicast ping-slot period (Class-B only).
	MulticastPingSlotPeriod uint32 `protobuf:"varint,5,opt,name=multicast_ping_slot_period,json=multicastPingSlotPeriod,proto3" json:"multicast_ping_slot_period,omitempty"`
	// Multicast frequency (Hz).
	MulticastFrequency uint32 `protobuf:"varint,6,opt,name=multicast_frequency,json=multicastFrequency,proto3" json:"multicast_frequency,omitempty"`
	// Multicast group ID.
	MulticastGroupId uint32 `protobuf:"varint,7,opt,name=multicast_group_id,json=multicastGroupId,proto3" json:"multicast_group_id,omitempty"`
	// Multicast timeout.
	// This defines the timeout of the multicast-session.
	// Please refer to the Remote Multicast Setup specification as this field
	// has a different meaning for Class-B and Class-C groups.
	MulticastTimeout uint32 `protobuf:"varint,8,opt,name=multicast_timeout,json=multicastTimeout,proto3" json:"multicast_timeout,omitempty"`
	// Unicast timeout.
	// Set this to the value in which you at least expect an uplink frame from
	// the device. The FUOTA server will wait for the given time before
	// attempting a retry or continuing with the next step.
	UnicastTimeout *duration.Duration `protobuf:"bytes,9,opt,name=unicast_timeout,json=unicastTimeout,proto3" json:"unicast_timeout,omitempty"`
	// Unicast attempt count.
	// The number of attempts before considering an unicast command
	// to be failed.
	UnicastAttemptCount uint32 `protobuf:"varint,10,opt,name=unicast_attempt_count,json=unicastAttemptCount,proto3" json:"unicast_attempt_count,omitempty"`
	// Multicast group id for devices to add into(if it exists).
	ExistingMulticastGroupId string `protobuf:"bytes,11,opt,name=existing_multicast_group_id,json=existingMulticastGroupId,proto3" json:"existing_multicast_group_id,omitempty"`
	// FS deployment db key, set if want to update a deployment.
	ExistingDeploymentId string   `protobuf:"bytes,12,opt,name=existing_deployment_id,json=existingDeploymentId,proto3" json:"existing_deployment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MulticastDeployment) Reset()         { *m = MulticastDeployment{} }
func (m *MulticastDeployment) String() string { return proto.CompactTextString(m) }
func (*MulticastDeployment) ProtoMessage()    {}
func (*MulticastDeployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{3}
}

func (m *MulticastDeployment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MulticastDeployment.Unmarshal(m, b)
}
func (m *MulticastDeployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MulticastDeployment.Marshal(b, m, deterministic)
}
func (m *MulticastDeployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MulticastDeployment.Merge(m, src)
}
func (m *MulticastDeployment) XXX_Size() int {
	return xxx_messageInfo_MulticastDeployment.Size(m)
}
func (m *MulticastDeployment) XXX_DiscardUnknown() {
	xxx_messageInfo_MulticastDeployment.DiscardUnknown(m)
}

var xxx_messageInfo_MulticastDeployment proto.InternalMessageInfo

func (m *MulticastDeployment) GetApplicationId() int64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *MulticastDeployment) GetDevices() []*DeploymentDevice {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *MulticastDeployment) GetMulticastGroupType() MulticastGroupType {
	if m != nil {
		return m.MulticastGroupType
	}
	return MulticastGroupType_CLASS_B
}

func (m *MulticastDeployment) GetMulticastDr() uint32 {
	if m != nil {
		return m.MulticastDr
	}
	return 0
}

func (m *MulticastDeployment) GetMulticastPingSlotPeriod() uint32 {
	if m != nil {
		return m.MulticastPingSlotPeriod
	}
	return 0
}

func (m *MulticastDeployment) GetMulticastFrequency() uint32 {
	if m != nil {
		return m.MulticastFrequency
	}
	return 0
}

func (m *MulticastDeployment) GetMulticastGroupId() uint32 {
	if m != nil {
		return m.MulticastGroupId
	}
	return 0
}

func (m *MulticastDeployment) GetMulticastTimeout() uint32 {
	if m != nil {
		return m.MulticastTimeout
	}
	return 0
}

func (m *MulticastDeployment) GetUnicastTimeout() *duration.Duration {
	if m != nil {
		return m.UnicastTimeout
	}
	return nil
}

func (m *MulticastDeployment) GetUnicastAttemptCount() uint32 {
	if m != nil {
		return m.UnicastAttemptCount
	}
	return 0
}

func (m *MulticastDeployment) GetExistingMulticastGroupId() string {
	if m != nil {
		return m.ExistingMulticastGroupId
	}
	return ""
}

func (m *MulticastDeployment) GetExistingDeploymentId() string {
	if m != nil {
		return m.ExistingDeploymentId
	}
	return ""
}

type BulkMulticastDeployment struct {
	// Application ID.
	ApplicationId int64 `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// Devices to include in this deployment.
	Devices []*BulkDeploymentDevice `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	// McRootKey.
	McRootKey string `protobuf:"bytes,3,opt,name=mc_root_key,json=mcRootKey,proto3" json:"mc_root_key,omitempty"`
	// Multicast data-rate.
	MulticastDr uint32 `protobuf:"varint,4,opt,name=multicast_dr,json=multicastDr,proto3" json:"multicast_dr,omitempty"`
	// Multicast frequency (Hz).
	MulticastFrequency uint32 `protobuf:"varint,5,opt,name=multicast_frequency,json=multicastFrequency,proto3" json:"multicast_frequency,omitempty"`
	// Multicast group ID.
	MulticastGroupId uint32 `protobuf:"varint,6,opt,name=multicast_group_id,json=multicastGroupId,proto3" json:"multicast_group_id,omitempty"`
	// Unicast timeout.
	// Set this to the value in which you at least expect an uplink frame from
	// the device. The FUOTA server will wait for the given time before
	// attempting a retry or continuing with the next step.
	UnicastTimeout uint32 `protobuf:"varint,7,opt,name=unicast_timeout,json=unicastTimeout,proto3" json:"unicast_timeout,omitempty"`
	// Unicast attempt count.
	// The number of attempts before considering an unicast command
	// to be failed.
	UnicastAttemptCount uint32 `protobuf:"varint,8,opt,name=unicast_attempt_count,json=unicastAttemptCount,proto3" json:"unicast_attempt_count,omitempty"`
	// Multicast group id for devices to add into(if it exists).
	ExistingMulticastGroupId string `protobuf:"bytes,9,opt,name=existing_multicast_group_id,json=existingMulticastGroupId,proto3" json:"existing_multicast_group_id,omitempty"`
	// FS deployment db key, set if want to update a deployment.
	ExistingDeploymentId string   `protobuf:"bytes,10,opt,name=existing_deployment_id,json=existingDeploymentId,proto3" json:"existing_deployment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkMulticastDeployment) Reset()         { *m = BulkMulticastDeployment{} }
func (m *BulkMulticastDeployment) String() string { return proto.CompactTextString(m) }
func (*BulkMulticastDeployment) ProtoMessage()    {}
func (*BulkMulticastDeployment) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{4}
}

func (m *BulkMulticastDeployment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkMulticastDeployment.Unmarshal(m, b)
}
func (m *BulkMulticastDeployment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkMulticastDeployment.Marshal(b, m, deterministic)
}
func (m *BulkMulticastDeployment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkMulticastDeployment.Merge(m, src)
}
func (m *BulkMulticastDeployment) XXX_Size() int {
	return xxx_messageInfo_BulkMulticastDeployment.Size(m)
}
func (m *BulkMulticastDeployment) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkMulticastDeployment.DiscardUnknown(m)
}

var xxx_messageInfo_BulkMulticastDeployment proto.InternalMessageInfo

func (m *BulkMulticastDeployment) GetApplicationId() int64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *BulkMulticastDeployment) GetDevices() []*BulkDeploymentDevice {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *BulkMulticastDeployment) GetMcRootKey() string {
	if m != nil {
		return m.McRootKey
	}
	return ""
}

func (m *BulkMulticastDeployment) GetMulticastDr() uint32 {
	if m != nil {
		return m.MulticastDr
	}
	return 0
}

func (m *BulkMulticastDeployment) GetMulticastFrequency() uint32 {
	if m != nil {
		return m.MulticastFrequency
	}
	return 0
}

func (m *BulkMulticastDeployment) GetMulticastGroupId() uint32 {
	if m != nil {
		return m.MulticastGroupId
	}
	return 0
}

func (m *BulkMulticastDeployment) GetUnicastTimeout() uint32 {
	if m != nil {
		return m.UnicastTimeout
	}
	return 0
}

func (m *BulkMulticastDeployment) GetUnicastAttemptCount() uint32 {
	if m != nil {
		return m.UnicastAttemptCount
	}
	return 0
}

func (m *BulkMulticastDeployment) GetExistingMulticastGroupId() string {
	if m != nil {
		return m.ExistingMulticastGroupId
	}
	return ""
}

func (m *BulkMulticastDeployment) GetExistingDeploymentId() string {
	if m != nil {
		return m.ExistingDeploymentId
	}
	return ""
}

type CreateDeploymentRequest struct {
	// Deployment.
	Deployment           *Deployment `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateDeploymentRequest) Reset()         { *m = CreateDeploymentRequest{} }
func (m *CreateDeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeploymentRequest) ProtoMessage()    {}
func (*CreateDeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{5}
}

func (m *CreateDeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeploymentRequest.Unmarshal(m, b)
}
func (m *CreateDeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeploymentRequest.Marshal(b, m, deterministic)
}
func (m *CreateDeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeploymentRequest.Merge(m, src)
}
func (m *CreateDeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeploymentRequest.Size(m)
}
func (m *CreateDeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeploymentRequest proto.InternalMessageInfo

func (m *CreateDeploymentRequest) GetDeployment() *Deployment {
	if m != nil {
		return m.Deployment
	}
	return nil
}

type CreateDeploymentResponse struct {
	// ID of the created deployment.
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeploymentResponse) Reset()         { *m = CreateDeploymentResponse{} }
func (m *CreateDeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDeploymentResponse) ProtoMessage()    {}
func (*CreateDeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{6}
}

func (m *CreateDeploymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeploymentResponse.Unmarshal(m, b)
}
func (m *CreateDeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeploymentResponse.Marshal(b, m, deterministic)
}
func (m *CreateDeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeploymentResponse.Merge(m, src)
}
func (m *CreateDeploymentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDeploymentResponse.Size(m)
}
func (m *CreateDeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeploymentResponse proto.InternalMessageInfo

func (m *CreateDeploymentResponse) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type CreateMulticastDeploymentRequest struct {
	// Deployment.
	Deployment           *MulticastDeployment `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateMulticastDeploymentRequest) Reset()         { *m = CreateMulticastDeploymentRequest{} }
func (m *CreateMulticastDeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMulticastDeploymentRequest) ProtoMessage()    {}
func (*CreateMulticastDeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{7}
}

func (m *CreateMulticastDeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMulticastDeploymentRequest.Unmarshal(m, b)
}
func (m *CreateMulticastDeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMulticastDeploymentRequest.Marshal(b, m, deterministic)
}
func (m *CreateMulticastDeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMulticastDeploymentRequest.Merge(m, src)
}
func (m *CreateMulticastDeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMulticastDeploymentRequest.Size(m)
}
func (m *CreateMulticastDeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMulticastDeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMulticastDeploymentRequest proto.InternalMessageInfo

func (m *CreateMulticastDeploymentRequest) GetDeployment() *MulticastDeployment {
	if m != nil {
		return m.Deployment
	}
	return nil
}

type CreateMulticastDeploymentResponse struct {
	// ID of the created deployment.
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Multicast group id if a mc group created
	MulticastGroupId     string   `protobuf:"bytes,2,opt,name=multicast_group_id,json=multicastGroupId,proto3" json:"multicast_group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMulticastDeploymentResponse) Reset()         { *m = CreateMulticastDeploymentResponse{} }
func (m *CreateMulticastDeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMulticastDeploymentResponse) ProtoMessage()    {}
func (*CreateMulticastDeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{8}
}

func (m *CreateMulticastDeploymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMulticastDeploymentResponse.Unmarshal(m, b)
}
func (m *CreateMulticastDeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMulticastDeploymentResponse.Marshal(b, m, deterministic)
}
func (m *CreateMulticastDeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMulticastDeploymentResponse.Merge(m, src)
}
func (m *CreateMulticastDeploymentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMulticastDeploymentResponse.Size(m)
}
func (m *CreateMulticastDeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMulticastDeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMulticastDeploymentResponse proto.InternalMessageInfo

func (m *CreateMulticastDeploymentResponse) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CreateMulticastDeploymentResponse) GetMulticastGroupId() string {
	if m != nil {
		return m.MulticastGroupId
	}
	return ""
}

type BulkMulticastDeploymentRequest struct {
	// Deployment.
	Deployment           *BulkMulticastDeployment `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *BulkMulticastDeploymentRequest) Reset()         { *m = BulkMulticastDeploymentRequest{} }
func (m *BulkMulticastDeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*BulkMulticastDeploymentRequest) ProtoMessage()    {}
func (*BulkMulticastDeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{9}
}

func (m *BulkMulticastDeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkMulticastDeploymentRequest.Unmarshal(m, b)
}
func (m *BulkMulticastDeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkMulticastDeploymentRequest.Marshal(b, m, deterministic)
}
func (m *BulkMulticastDeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkMulticastDeploymentRequest.Merge(m, src)
}
func (m *BulkMulticastDeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_BulkMulticastDeploymentRequest.Size(m)
}
func (m *BulkMulticastDeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkMulticastDeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BulkMulticastDeploymentRequest proto.InternalMessageInfo

func (m *BulkMulticastDeploymentRequest) GetDeployment() *BulkMulticastDeployment {
	if m != nil {
		return m.Deployment
	}
	return nil
}

type BulkMulticastDeploymentResponse struct {
	// ID of the created deployment.
	NumberOfDevices uint32 `protobuf:"varint,1,opt,name=number_of_devices,json=numberOfDevices,proto3" json:"number_of_devices,omitempty"`
	// Multicast group id if a mc group created
	MulticastGroupId string `protobuf:"bytes,2,opt,name=multicast_group_id,json=multicastGroupId,proto3" json:"multicast_group_id,omitempty"`
	// Deployment id of the fuota server deployment object
	DeploymentId         string   `protobuf:"bytes,3,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BulkMulticastDeploymentResponse) Reset()         { *m = BulkMulticastDeploymentResponse{} }
func (m *BulkMulticastDeploymentResponse) String() string { return proto.CompactTextString(m) }
func (*BulkMulticastDeploymentResponse) ProtoMessage()    {}
func (*BulkMulticastDeploymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{10}
}

func (m *BulkMulticastDeploymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkMulticastDeploymentResponse.Unmarshal(m, b)
}
func (m *BulkMulticastDeploymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkMulticastDeploymentResponse.Marshal(b, m, deterministic)
}
func (m *BulkMulticastDeploymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkMulticastDeploymentResponse.Merge(m, src)
}
func (m *BulkMulticastDeploymentResponse) XXX_Size() int {
	return xxx_messageInfo_BulkMulticastDeploymentResponse.Size(m)
}
func (m *BulkMulticastDeploymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkMulticastDeploymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BulkMulticastDeploymentResponse proto.InternalMessageInfo

func (m *BulkMulticastDeploymentResponse) GetNumberOfDevices() uint32 {
	if m != nil {
		return m.NumberOfDevices
	}
	return 0
}

func (m *BulkMulticastDeploymentResponse) GetMulticastGroupId() string {
	if m != nil {
		return m.MulticastGroupId
	}
	return ""
}

func (m *BulkMulticastDeploymentResponse) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

type GetDeploymentStatusRequest struct {
	// Deployment ID.
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeploymentStatusRequest) Reset()         { *m = GetDeploymentStatusRequest{} }
func (m *GetDeploymentStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeploymentStatusRequest) ProtoMessage()    {}
func (*GetDeploymentStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{11}
}

func (m *GetDeploymentStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeploymentStatusRequest.Unmarshal(m, b)
}
func (m *GetDeploymentStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeploymentStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetDeploymentStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeploymentStatusRequest.Merge(m, src)
}
func (m *GetDeploymentStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeploymentStatusRequest.Size(m)
}
func (m *GetDeploymentStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeploymentStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeploymentStatusRequest proto.InternalMessageInfo

func (m *GetDeploymentStatusRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeploymentDeviceStatus struct {
	// DevEUI.
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Created at.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated at.
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Multicast-group setup completed at.
	McGroupSetupCompletedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=mc_group_setup_completed_at,json=mcGroupSetupCompletedAt,proto3" json:"mc_group_setup_completed_at,omitempty"`
	// Multicast-session completed at.
	McSessionCompletedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=mc_session_completed_at,json=mcSessionCompletedAt,proto3" json:"mc_session_completed_at,omitempty"`
	// Fragmentation session setup completed at.
	FragSessionSetupCompletedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=frag_session_setup_completed_at,json=fragSessionSetupCompletedAt,proto3" json:"frag_session_setup_completed_at,omitempty"`
	// Fragmentation status completed at.
	FragStatusCompletedAt *timestamp.Timestamp `protobuf:"bytes,7,opt,name=frag_status_completed_at,json=fragStatusCompletedAt,proto3" json:"frag_status_completed_at,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *DeploymentDeviceStatus) Reset()         { *m = DeploymentDeviceStatus{} }
func (m *DeploymentDeviceStatus) String() string { return proto.CompactTextString(m) }
func (*DeploymentDeviceStatus) ProtoMessage()    {}
func (*DeploymentDeviceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{12}
}

func (m *DeploymentDeviceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentDeviceStatus.Unmarshal(m, b)
}
func (m *DeploymentDeviceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentDeviceStatus.Marshal(b, m, deterministic)
}
func (m *DeploymentDeviceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentDeviceStatus.Merge(m, src)
}
func (m *DeploymentDeviceStatus) XXX_Size() int {
	return xxx_messageInfo_DeploymentDeviceStatus.Size(m)
}
func (m *DeploymentDeviceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentDeviceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentDeviceStatus proto.InternalMessageInfo

func (m *DeploymentDeviceStatus) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *DeploymentDeviceStatus) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *DeploymentDeviceStatus) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *DeploymentDeviceStatus) GetMcGroupSetupCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.McGroupSetupCompletedAt
	}
	return nil
}

func (m *DeploymentDeviceStatus) GetMcSessionCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.McSessionCompletedAt
	}
	return nil
}

func (m *DeploymentDeviceStatus) GetFragSessionSetupCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.FragSessionSetupCompletedAt
	}
	return nil
}

func (m *DeploymentDeviceStatus) GetFragStatusCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.FragStatusCompletedAt
	}
	return nil
}

type GetDeploymentStatusResponse struct {
	// Created at.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated at.
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Multicast-group setup completed at.
	McGroupSetupCompletedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=mc_group_setup_completed_at,json=mcGroupSetupCompletedAt,proto3" json:"mc_group_setup_completed_at,omitempty"`
	// Multicast-session completed at.
	McSessionCompletedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=mc_session_completed_at,json=mcSessionCompletedAt,proto3" json:"mc_session_completed_at,omitempty"`
	// Fragmentation session setup completed at.
	FragSessionSetupCompletedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=frag_session_setup_completed_at,json=fragSessionSetupCompletedAt,proto3" json:"frag_session_setup_completed_at,omitempty"`
	// Enqueue completed at.
	EnqueueCompletedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=enqueue_completed_at,json=enqueueCompletedAt,proto3" json:"enqueue_completed_at,omitempty"`
	// Fragmentation status completed at.
	FragStatusCompletedAt *timestamp.Timestamp `protobuf:"bytes,7,opt,name=frag_status_completed_at,json=fragStatusCompletedAt,proto3" json:"frag_status_completed_at,omitempty"`
	// Per device status.
	DeviceStatus         []*DeploymentDeviceStatus `protobuf:"bytes,8,rep,name=device_status,json=deviceStatus,proto3" json:"device_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetDeploymentStatusResponse) Reset()         { *m = GetDeploymentStatusResponse{} }
func (m *GetDeploymentStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeploymentStatusResponse) ProtoMessage()    {}
func (*GetDeploymentStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{13}
}

func (m *GetDeploymentStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeploymentStatusResponse.Unmarshal(m, b)
}
func (m *GetDeploymentStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeploymentStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetDeploymentStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeploymentStatusResponse.Merge(m, src)
}
func (m *GetDeploymentStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeploymentStatusResponse.Size(m)
}
func (m *GetDeploymentStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeploymentStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeploymentStatusResponse proto.InternalMessageInfo

func (m *GetDeploymentStatusResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *GetDeploymentStatusResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *GetDeploymentStatusResponse) GetMcGroupSetupCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.McGroupSetupCompletedAt
	}
	return nil
}

func (m *GetDeploymentStatusResponse) GetMcSessionCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.McSessionCompletedAt
	}
	return nil
}

func (m *GetDeploymentStatusResponse) GetFragSessionSetupCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.FragSessionSetupCompletedAt
	}
	return nil
}

func (m *GetDeploymentStatusResponse) GetEnqueueCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.EnqueueCompletedAt
	}
	return nil
}

func (m *GetDeploymentStatusResponse) GetFragStatusCompletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.FragStatusCompletedAt
	}
	return nil
}

func (m *GetDeploymentStatusResponse) GetDeviceStatus() []*DeploymentDeviceStatus {
	if m != nil {
		return m.DeviceStatus
	}
	return nil
}

type GetDeploymentDeviceLogsRequest struct {
	// Deployment ID.
	DeploymentId []byte `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	// DevEUI.
	DevEui               []byte   `protobuf:"bytes,2,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeploymentDeviceLogsRequest) Reset()         { *m = GetDeploymentDeviceLogsRequest{} }
func (m *GetDeploymentDeviceLogsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeploymentDeviceLogsRequest) ProtoMessage()    {}
func (*GetDeploymentDeviceLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{14}
}

func (m *GetDeploymentDeviceLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeploymentDeviceLogsRequest.Unmarshal(m, b)
}
func (m *GetDeploymentDeviceLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeploymentDeviceLogsRequest.Marshal(b, m, deterministic)
}
func (m *GetDeploymentDeviceLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeploymentDeviceLogsRequest.Merge(m, src)
}
func (m *GetDeploymentDeviceLogsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeploymentDeviceLogsRequest.Size(m)
}
func (m *GetDeploymentDeviceLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeploymentDeviceLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeploymentDeviceLogsRequest proto.InternalMessageInfo

func (m *GetDeploymentDeviceLogsRequest) GetDeploymentId() []byte {
	if m != nil {
		return m.DeploymentId
	}
	return nil
}

func (m *GetDeploymentDeviceLogsRequest) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

type DeploymentDeviceLog struct {
	// Created at.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// FPort.
	FPort uint32 `protobuf:"varint,2,opt,name=f_port,json=fPort,proto3" json:"f_port,omitempty"`
	// Command.
	Command string `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	// Fields.
	Fields               map[string]string `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeploymentDeviceLog) Reset()         { *m = DeploymentDeviceLog{} }
func (m *DeploymentDeviceLog) String() string { return proto.CompactTextString(m) }
func (*DeploymentDeviceLog) ProtoMessage()    {}
func (*DeploymentDeviceLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{15}
}

func (m *DeploymentDeviceLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentDeviceLog.Unmarshal(m, b)
}
func (m *DeploymentDeviceLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentDeviceLog.Marshal(b, m, deterministic)
}
func (m *DeploymentDeviceLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentDeviceLog.Merge(m, src)
}
func (m *DeploymentDeviceLog) XXX_Size() int {
	return xxx_messageInfo_DeploymentDeviceLog.Size(m)
}
func (m *DeploymentDeviceLog) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentDeviceLog.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentDeviceLog proto.InternalMessageInfo

func (m *DeploymentDeviceLog) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *DeploymentDeviceLog) GetFPort() uint32 {
	if m != nil {
		return m.FPort
	}
	return 0
}

func (m *DeploymentDeviceLog) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *DeploymentDeviceLog) GetFields() map[string]string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetDeploymentDeviceLogsResponse struct {
	Logs                 []*DeploymentDeviceLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetDeploymentDeviceLogsResponse) Reset()         { *m = GetDeploymentDeviceLogsResponse{} }
func (m *GetDeploymentDeviceLogsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeploymentDeviceLogsResponse) ProtoMessage()    {}
func (*GetDeploymentDeviceLogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{16}
}

func (m *GetDeploymentDeviceLogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeploymentDeviceLogsResponse.Unmarshal(m, b)
}
func (m *GetDeploymentDeviceLogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeploymentDeviceLogsResponse.Marshal(b, m, deterministic)
}
func (m *GetDeploymentDeviceLogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeploymentDeviceLogsResponse.Merge(m, src)
}
func (m *GetDeploymentDeviceLogsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeploymentDeviceLogsResponse.Size(m)
}
func (m *GetDeploymentDeviceLogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeploymentDeviceLogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeploymentDeviceLogsResponse proto.InternalMessageInfo

func (m *GetDeploymentDeviceLogsResponse) GetLogs() []*DeploymentDeviceLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

type ResetMulticastSetupRequest struct {
	// Deployment id of the fuota server deployment object
	DeploymentId string `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	// DevEUI.
	DevEui               string   `protobuf:"bytes,2,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetMulticastSetupRequest) Reset()         { *m = ResetMulticastSetupRequest{} }
func (m *ResetMulticastSetupRequest) String() string { return proto.CompactTextString(m) }
func (*ResetMulticastSetupRequest) ProtoMessage()    {}
func (*ResetMulticastSetupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{17}
}

func (m *ResetMulticastSetupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetMulticastSetupRequest.Unmarshal(m, b)
}
func (m *ResetMulticastSetupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetMulticastSetupRequest.Marshal(b, m, deterministic)
}
func (m *ResetMulticastSetupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetMulticastSetupRequest.Merge(m, src)
}
func (m *ResetMulticastSetupRequest) XXX_Size() int {
	return xxx_messageInfo_ResetMulticastSetupRequest.Size(m)
}
func (m *ResetMulticastSetupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetMulticastSetupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetMulticastSetupRequest proto.InternalMessageInfo

func (m *ResetMulticastSetupRequest) GetDeploymentId() string {
	if m != nil {
		return m.DeploymentId
	}
	return ""
}

func (m *ResetMulticastSetupRequest) GetDevEui() string {
	if m != nil {
		return m.DevEui
	}
	return ""
}

type ResetMulticastSetupResponse struct {
	// Is succeed.
	IsSucceed            bool     `protobuf:"varint,1,opt,name=isSucceed,proto3" json:"isSucceed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetMulticastSetupResponse) Reset()         { *m = ResetMulticastSetupResponse{} }
func (m *ResetMulticastSetupResponse) String() string { return proto.CompactTextString(m) }
func (*ResetMulticastSetupResponse) ProtoMessage()    {}
func (*ResetMulticastSetupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5169117df74b07cc, []int{18}
}

func (m *ResetMulticastSetupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetMulticastSetupResponse.Unmarshal(m, b)
}
func (m *ResetMulticastSetupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetMulticastSetupResponse.Marshal(b, m, deterministic)
}
func (m *ResetMulticastSetupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetMulticastSetupResponse.Merge(m, src)
}
func (m *ResetMulticastSetupResponse) XXX_Size() int {
	return xxx_messageInfo_ResetMulticastSetupResponse.Size(m)
}
func (m *ResetMulticastSetupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetMulticastSetupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetMulticastSetupResponse proto.InternalMessageInfo

func (m *ResetMulticastSetupResponse) GetIsSucceed() bool {
	if m != nil {
		return m.IsSucceed
	}
	return false
}

func init() {
	proto.RegisterEnum("fuota.MulticastGroupType", MulticastGroupType_name, MulticastGroupType_value)
	proto.RegisterEnum("fuota.RequestFragmentationSessionStatus", RequestFragmentationSessionStatus_name, RequestFragmentationSessionStatus_value)
	proto.RegisterType((*DeploymentDevice)(nil), "fuota.DeploymentDevice")
	proto.RegisterType((*BulkDeploymentDevice)(nil), "fuota.BulkDeploymentDevice")
	proto.RegisterType((*Deployment)(nil), "fuota.Deployment")
	proto.RegisterType((*MulticastDeployment)(nil), "fuota.MulticastDeployment")
	proto.RegisterType((*BulkMulticastDeployment)(nil), "fuota.BulkMulticastDeployment")
	proto.RegisterType((*CreateDeploymentRequest)(nil), "fuota.CreateDeploymentRequest")
	proto.RegisterType((*CreateDeploymentResponse)(nil), "fuota.CreateDeploymentResponse")
	proto.RegisterType((*CreateMulticastDeploymentRequest)(nil), "fuota.CreateMulticastDeploymentRequest")
	proto.RegisterType((*CreateMulticastDeploymentResponse)(nil), "fuota.CreateMulticastDeploymentResponse")
	proto.RegisterType((*BulkMulticastDeploymentRequest)(nil), "fuota.BulkMulticastDeploymentRequest")
	proto.RegisterType((*BulkMulticastDeploymentResponse)(nil), "fuota.BulkMulticastDeploymentResponse")
	proto.RegisterType((*GetDeploymentStatusRequest)(nil), "fuota.GetDeploymentStatusRequest")
	proto.RegisterType((*DeploymentDeviceStatus)(nil), "fuota.DeploymentDeviceStatus")
	proto.RegisterType((*GetDeploymentStatusResponse)(nil), "fuota.GetDeploymentStatusResponse")
	proto.RegisterType((*GetDeploymentDeviceLogsRequest)(nil), "fuota.GetDeploymentDeviceLogsRequest")
	proto.RegisterType((*DeploymentDeviceLog)(nil), "fuota.DeploymentDeviceLog")
	proto.RegisterMapType((map[string]string)(nil), "fuota.DeploymentDeviceLog.FieldsEntry")
	proto.RegisterType((*GetDeploymentDeviceLogsResponse)(nil), "fuota.GetDeploymentDeviceLogsResponse")
	proto.RegisterType((*ResetMulticastSetupRequest)(nil), "fuota.ResetMulticastSetupRequest")
	proto.RegisterType((*ResetMulticastSetupResponse)(nil), "fuota.ResetMulticastSetupResponse")
}

func init() {
	proto.RegisterFile("fuota/fuota.proto", fileDescriptor_5169117df74b07cc)
}

var fileDescriptor_5169117df74b07cc = []byte{
	// 1553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x4b, 0x6f, 0xdb, 0xc6,
	0x13, 0xb7, 0x24, 0xcb, 0x8f, 0x91, 0xed, 0xc8, 0x6b, 0x3b, 0xa2, 0xe5, 0x7f, 0xfc, 0xe0, 0xbf,
	0x4d, 0x0c, 0x37, 0x91, 0x10, 0xa7, 0x05, 0x9a, 0x04, 0x0d, 0x20, 0xdb, 0x72, 0x6a, 0xc4, 0x8f,
	0x98, 0x92, 0x81, 0x22, 0x87, 0x30, 0x34, 0xb9, 0x52, 0x18, 0x8b, 0x5a, 0x86, 0x5c, 0x1a, 0x51,
	0xbe, 0x41, 0xd1, 0x73, 0x81, 0x1e, 0xfb, 0xfd, 0x7a, 0xee, 0xad, 0x87, 0x82, 0xbb, 0x4b, 0x52,
	0x94, 0x48, 0x29, 0x8f, 0xe6, 0x96, 0x8b, 0xe1, 0xdd, 0xf9, 0xcd, 0xec, 0x3c, 0x7e, 0x3b, 0x3b,
	0x14, 0x2c, 0xb6, 0x3c, 0x42, 0xb5, 0x2a, 0xfb, 0x5b, 0xb1, 0x1d, 0x42, 0x09, 0xca, 0xb3, 0x45,
	0x79, 0xa3, 0x4d, 0x48, 0xbb, 0x83, 0xab, 0x6c, 0xf3, 0xd2, 0x6b, 0x55, 0xa9, 0x69, 0x61, 0x97,
	0x6a, 0x96, 0xcd, 0x71, 0xe5, 0xf5, 0x41, 0x80, 0xe1, 0x39, 0x1a, 0x35, 0x49, 0x97, 0xcb, 0xe5,
	0x67, 0x50, 0x3c, 0xc0, 0x76, 0x87, 0xf4, 0x2c, 0xdc, 0xa5, 0x07, 0xf8, 0xda, 0xd4, 0x31, 0x2a,
	0xc1, 0xb4, 0x81, 0xaf, 0x55, 0xec, 0x99, 0x52, 0x66, 0x33, 0xb3, 0x3d, 0xa7, 0x4c, 0x19, 0xf8,
	0xba, 0xee, 0x99, 0x68, 0x1d, 0x0a, 0x96, 0xae, 0x3a, 0x84, 0x50, 0xf5, 0x0a, 0xf7, 0xa4, 0x2c,
	0x13, 0xce, 0x5a, 0xba, 0x42, 0x08, 0x7d, 0x86, 0x7b, 0x72, 0x15, 0x96, 0xf7, 0xbc, 0xce, 0xd5,
	0x38, 0x83, 0xb3, 0x81, 0x41, 0xf9, 0x8f, 0x19, 0x80, 0x08, 0x8d, 0xbe, 0x85, 0x05, 0xcd, 0xb6,
	0x3b, 0xa6, 0xce, 0x3c, 0x54, 0x4d, 0x83, 0xc1, 0x73, 0xca, 0x7c, 0xdf, 0xee, 0x91, 0x81, 0xee,
	0x33, 0x73, 0xa6, 0x8e, 0x5d, 0x29, 0xbb, 0x99, 0xdb, 0x2e, 0xec, 0x96, 0x2a, 0x3c, 0x35, 0x83,
	0x07, 0x2b, 0x01, 0x0e, 0x3d, 0x83, 0x65, 0xcb, 0xeb, 0x50, 0x53, 0xd7, 0x5c, 0xaa, 0xb6, 0x1d,
	0xe2, 0xd9, 0x2a, 0xed, 0xd9, 0x58, 0xca, 0x6d, 0x66, 0xb6, 0x17, 0x76, 0x57, 0x85, 0xfe, 0x49,
	0x00, 0x79, 0xea, 0x23, 0x9a, 0x3d, 0x1b, 0x2b, 0xc8, 0x1a, 0xda, 0x43, 0x5b, 0x30, 0x17, 0x19,
	0x33, 0x1c, 0x69, 0x72, 0x33, 0xb3, 0x3d, 0xaf, 0x14, 0xc2, 0xbd, 0x03, 0x07, 0x3d, 0x86, 0x72,
	0x04, 0xb1, 0xcd, 0x6e, 0x5b, 0x75, 0x3b, 0x84, 0xaa, 0x36, 0x76, 0x4c, 0x62, 0x48, 0x79, 0xa6,
	0x50, 0x0a, 0x11, 0xcf, 0xcd, 0x6e, 0xbb, 0xd1, 0x21, 0xf4, 0x39, 0x13, 0xa3, 0x2a, 0x2c, 0x45,
	0xca, 0x2d, 0x07, 0xbf, 0xf5, 0x70, 0x57, 0xef, 0x49, 0x53, 0x4c, 0x2b, 0x72, 0xe8, 0x30, 0x90,
	0xa0, 0xbb, 0x80, 0x06, 0xa3, 0x33, 0x0d, 0x69, 0x9a, 0xe1, 0x8b, 0xf1, 0x00, 0x8e, 0x0c, 0xf4,
	0x1d, 0x2c, 0x46, 0x68, 0x9f, 0x2f, 0xc4, 0xa3, 0xd2, 0xcc, 0x00, 0xb8, 0xc9, 0xf7, 0xd1, 0x1e,
	0xdc, 0xf0, 0xba, 0x71, 0xe8, 0xec, 0x66, 0x66, 0xbb, 0xb0, 0xbb, 0x5a, 0xe1, 0xcc, 0xaa, 0x04,
	0xcc, 0xaa, 0x1c, 0x08, 0x66, 0x29, 0x0b, 0x42, 0x23, 0xb0, 0xb1, 0x0b, 0x2b, 0x81, 0x0d, 0x8d,
	0x52, 0x6c, 0xd9, 0x54, 0xd5, 0x89, 0xd7, 0xa5, 0x12, 0xb0, 0x43, 0x97, 0x84, 0xb0, 0xc6, 0x65,
	0xfb, 0xbe, 0x08, 0x3d, 0x81, 0xb5, 0x96, 0xa3, 0xb5, 0xfd, 0x5a, 0x72, 0x32, 0x04, 0x2b, 0xd5,
	0x35, 0xdf, 0x63, 0xa9, 0xc0, 0x34, 0x57, 0x63, 0x90, 0x43, 0xb1, 0x68, 0x98, 0xef, 0x31, 0x92,
	0x60, 0xda, 0xd6, 0x7a, 0x1d, 0xa2, 0x19, 0xd2, 0x1c, 0xa3, 0x69, 0xb0, 0x44, 0x0f, 0x41, 0x8a,
	0x5b, 0x76, 0xb0, 0xe1, 0x75, 0x0d, 0xcd, 0x4f, 0xf1, 0x3c, 0x2f, 0x4c, 0x4c, 0xae, 0x84, 0xe2,
	0x61, 0xa7, 0x5c, 0xec, 0xba, 0x8c, 0xa9, 0x5d, 0x03, 0xbf, 0x93, 0x16, 0x12, 0x9c, 0x6a, 0x70,
	0xc4, 0x91, 0x0f, 0x40, 0xf7, 0x61, 0x39, 0xae, 0x6f, 0x69, 0xd4, 0x31, 0xdf, 0x49, 0x37, 0x78,
	0x1e, 0x62, 0xb2, 0x13, 0x26, 0x42, 0x35, 0xb8, 0x15, 0x57, 0xb9, 0xec, 0x10, 0xfd, 0x4a, 0xd5,
	0xf4, 0x2b, 0xd5, 0xc0, 0x1d, 0xad, 0x27, 0x15, 0x99, 0x6e, 0x39, 0x06, 0xda, 0xf3, 0x31, 0x35,
	0xfd, 0xea, 0xc0, 0x47, 0x0c, 0x07, 0x6c, 0x60, 0x57, 0x77, 0x4c, 0x9b, 0x12, 0x47, 0x5a, 0x64,
	0xb9, 0x89, 0x07, 0x7c, 0x10, 0x8a, 0x51, 0x0f, 0xbe, 0x61, 0x24, 0x63, 0x3c, 0x4c, 0x0a, 0xdc,
	0xa5, 0x1a, 0xf5, 0x5c, 0x09, 0xb1, 0x6b, 0xb4, 0x2d, 0xae, 0x91, 0xc2, 0x55, 0x0e, 0x13, 0xf2,
	0xd0, 0x60, 0x78, 0x65, 0xcb, 0x19, 0x07, 0x91, 0x7f, 0xcf, 0xc3, 0x52, 0x78, 0x1f, 0xbf, 0xf6,
	0x88, 0xaf, 0x3d, 0x62, 0xb8, 0x47, 0xfc, 0x04, 0x6b, 0xf8, 0x9d, 0xe9, 0x52, 0x3f, 0x75, 0x09,
	0xb1, 0x15, 0xd8, 0x53, 0x23, 0x05, 0x90, 0x93, 0xc1, 0x18, 0xbf, 0x87, 0x9b, 0xa1, 0xba, 0x11,
	0xb2, 0xc2, 0xd7, 0x9c, 0x63, 0x9a, 0xcb, 0x81, 0x34, 0xa2, 0xcc, 0x91, 0x21, 0xff, 0x95, 0x83,
	0x92, 0xff, 0xc8, 0x7d, 0x06, 0x37, 0x7f, 0x18, 0xe4, 0xe6, 0x9a, 0xe0, 0x56, 0xd2, 0xe3, 0x19,
	0xf1, 0x73, 0xe0, 0xf5, 0xcd, 0x31, 0x27, 0xa3, 0xd7, 0xf7, 0x43, 0x28, 0x97, 0xc2, 0x9a, 0xfc,
	0x47, 0xb2, 0x66, 0x2a, 0x85, 0x35, 0x77, 0x86, 0x89, 0xc0, 0x09, 0xf6, 0xc1, 0xd5, 0x9e, 0xf9,
	0xe4, 0x6a, 0xcf, 0x7e, 0x72, 0xb5, 0x61, 0x44, 0xb5, 0x8f, 0xa1, 0xb4, 0xef, 0x60, 0x8d, 0xe2,
	0x68, 0x57, 0x74, 0x37, 0x74, 0x1f, 0x20, 0xb2, 0xc3, 0x0a, 0x5d, 0xd8, 0x5d, 0x1c, 0x6a, 0x32,
	0x4a, 0x1f, 0x48, 0xde, 0x01, 0x69, 0xd8, 0x9a, 0x6b, 0x93, 0xae, 0x8b, 0xd1, 0x02, 0x64, 0x05,
	0x5f, 0xe6, 0x94, 0xac, 0x69, 0xc8, 0x2f, 0x61, 0x93, 0x63, 0x13, 0x88, 0x16, 0xb8, 0xf0, 0x28,
	0xc1, 0x85, 0xf2, 0x60, 0x9f, 0x4a, 0xf1, 0x45, 0x83, 0xad, 0x11, 0xf6, 0x93, 0x9d, 0x4a, 0xa1,
	0x43, 0x96, 0x25, 0x70, 0x88, 0x0e, 0xf2, 0x2b, 0x58, 0x4f, 0xb9, 0x29, 0x41, 0x00, 0x4f, 0x12,
	0x02, 0x58, 0xef, 0xbb, 0x0c, 0xe3, 0x82, 0xf8, 0x33, 0x03, 0x1b, 0xa9, 0x47, 0x88, 0x18, 0x76,
	0x60, 0xb1, 0xeb, 0x59, 0x97, 0xd8, 0x51, 0x49, 0x4b, 0x0d, 0xee, 0x5d, 0x86, 0xf1, 0xec, 0x06,
	0x17, 0x9c, 0xb5, 0x0e, 0xc4, 0x15, 0xfb, 0xa8, 0xf8, 0xd0, 0xff, 0x61, 0x3e, 0xce, 0x24, 0x7e,
	0x25, 0xe7, 0x8c, 0x7e, 0x06, 0xdd, 0x85, 0xf2, 0x53, 0xdc, 0xe7, 0x97, 0x78, 0x01, 0x45, 0x02,
	0x06, 0xab, 0xfe, 0xdb, 0x24, 0xdc, 0x1c, 0xec, 0x00, 0x5c, 0x23, 0x7d, 0x2a, 0x7f, 0x08, 0xa0,
	0xb3, 0x4a, 0x1a, 0xaa, 0x46, 0x99, 0xb3, 0x3e, 0x0b, 0x06, 0x3b, 0x6f, 0x33, 0xf8, 0x30, 0x50,
	0x66, 0x05, 0xba, 0x46, 0x7d, 0x55, 0xcf, 0x36, 0x02, 0xd5, 0xdc, 0x78, 0x55, 0x81, 0xae, 0x51,
	0xf4, 0x0b, 0xac, 0x59, 0xba, 0xc8, 0x91, 0x8b, 0xa9, 0x67, 0xab, 0x3a, 0xb1, 0xec, 0x0e, 0x16,
	0xb6, 0x26, 0xc7, 0xda, 0x2a, 0x59, 0x3a, 0x4b, 0x64, 0xc3, 0x57, 0xde, 0x0f, 0x74, 0x6b, 0x14,
	0x9d, 0x43, 0xc9, 0xd2, 0xc3, 0x09, 0x23, 0x66, 0x35, 0x3f, 0xd6, 0xea, 0xb2, 0xa5, 0x8b, 0x39,
	0xa2, 0xdf, 0xe4, 0x2b, 0xd8, 0xf0, 0xe7, 0x97, 0x68, 0x6c, 0x19, 0x76, 0x78, 0x6a, 0xac, 0x69,
	0x36, 0xfb, 0x05, 0x43, 0xca, 0xa0, 0xd3, 0x0d, 0x3e, 0x64, 0x89, 0x81, 0x28, 0x6e, 0x7a, 0x7a,
	0xac, 0xe9, 0x15, 0x66, 0x9a, 0xa9, 0xf6, 0x19, 0x95, 0x7f, 0xcd, 0xc3, 0x5a, 0x22, 0x79, 0x04,
	0xb5, 0xe3, 0x95, 0xcf, 0x7c, 0x7a, 0xe5, 0xb3, 0xff, 0x61, 0xe5, 0x73, 0x5f, 0xa4, 0xf2, 0x93,
	0x5f, 0xae, 0xf2, 0xf9, 0xcf, 0xab, 0xfc, 0x31, 0x2c, 0xe3, 0xee, 0x5b, 0x0f, 0x7b, 0xf8, 0x63,
	0x09, 0x85, 0x84, 0xde, 0x97, 0xe6, 0x11, 0xda, 0xf3, 0x1b, 0x95, 0xdf, 0x4a, 0x82, 0x79, 0x7d,
	0x86, 0x8d, 0x1d, 0xb7, 0x52, 0x46, 0x62, 0xc1, 0xb2, 0x39, 0xa3, 0x6f, 0x25, 0xbf, 0x84, 0xf5,
	0x18, 0x15, 0x39, 0xf4, 0x98, 0xb4, 0xc3, 0x5e, 0x36, 0xd4, 0x0e, 0x79, 0x9b, 0x8a, 0xb5, 0xc3,
	0xfe, 0x2e, 0x96, 0xed, 0xef, 0x62, 0xf2, 0x3f, 0x19, 0x58, 0x4a, 0xb0, 0xfe, 0x39, 0x1c, 0x5f,
	0x81, 0xa9, 0x96, 0x6a, 0x13, 0x87, 0xf3, 0x7b, 0x5e, 0xc9, 0xb7, 0x9e, 0x13, 0x87, 0xfa, 0x9f,
	0x86, 0x3a, 0xb1, 0x2c, 0xad, 0x1b, 0x34, 0xec, 0x60, 0x89, 0x9e, 0xc0, 0x54, 0xcb, 0xc4, 0x1d,
	0xc3, 0x95, 0x26, 0x59, 0x82, 0x6e, 0xa7, 0x24, 0xe8, 0x98, 0xb4, 0x2b, 0x87, 0x0c, 0x58, 0xef,
	0x52, 0xa7, 0xa7, 0x08, 0xad, 0xf2, 0x43, 0x28, 0xf4, 0x6d, 0xa3, 0x22, 0xe4, 0xfc, 0x41, 0x8d,
	0xff, 0xe4, 0xe1, 0xff, 0x8b, 0x96, 0x21, 0x7f, 0xad, 0x75, 0x3c, 0x2c, 0x9e, 0x14, 0xbe, 0x78,
	0x94, 0xfd, 0x31, 0x23, 0x9f, 0xc3, 0x46, 0x6a, 0x7a, 0xc5, 0x6d, 0xaf, 0xc0, 0x64, 0x87, 0xb4,
	0xfd, 0xb7, 0x2b, 0xd7, 0xf7, 0xce, 0x27, 0xa8, 0x28, 0x0c, 0x27, 0xbf, 0x80, 0xb2, 0x82, 0x5d,
	0x4c, 0xc3, 0xc7, 0x91, 0x51, 0x77, 0x64, 0xb5, 0x66, 0x47, 0x57, 0x2b, 0xfa, 0xe1, 0xe6, 0x31,
	0xac, 0x25, 0xda, 0x16, 0xae, 0xfe, 0x0f, 0x66, 0x4d, 0xb7, 0xe1, 0xe9, 0x3a, 0xc6, 0xdc, 0xf0,
	0x8c, 0x12, 0x6d, 0xec, 0x54, 0x00, 0x0d, 0x7f, 0x45, 0xa1, 0x02, 0x4c, 0xef, 0x1f, 0xd7, 0x1a,
	0x0d, 0x75, 0xaf, 0x38, 0x11, 0x2d, 0xf6, 0x8b, 0x99, 0x9d, 0x37, 0xb0, 0x35, 0xf6, 0x93, 0x12,
	0x95, 0xe1, 0x66, 0xed, 0xb0, 0x59, 0x57, 0xd4, 0x43, 0xa5, 0xf6, 0xf4, 0xa4, 0x7e, 0xda, 0x54,
	0xeb, 0xa7, 0xe7, 0x17, 0xf5, 0x8b, 0x7a, 0x71, 0x02, 0xad, 0xc2, 0x0a, 0x97, 0x35, 0xea, 0x8d,
	0xc6, 0xd1, 0xd9, 0xa9, 0xda, 0x3c, 0x3a, 0xa9, 0x9f, 0x5d, 0x34, 0x8b, 0x19, 0xb4, 0x00, 0x70,
	0x7a, 0xa6, 0x2a, 0xf5, 0xf3, 0x8b, 0x7a, 0xa3, 0x59, 0xcc, 0xee, 0xfe, 0x3d, 0x09, 0xe8, 0xf0,
	0xe2, 0xac, 0x59, 0x6b, 0x60, 0xe7, 0x1a, 0x3b, 0xfe, 0x5f, 0x53, 0xc7, 0xe8, 0x02, 0x8a, 0x83,
	0x93, 0x1b, 0x0a, 0x06, 0x95, 0x94, 0x01, 0xb1, 0xbc, 0x91, 0x2a, 0xe7, 0x59, 0x92, 0x27, 0x90,
	0x0d, 0xab, 0xa9, 0x43, 0x18, 0xba, 0x13, 0xd3, 0x4f, 0x9f, 0xa2, 0xca, 0xdb, 0xe3, 0x81, 0xe1,
	0x89, 0x6f, 0x46, 0x7c, 0xbd, 0x8c, 0x19, 0xbc, 0xc4, 0x69, 0xb7, 0xc7, 0xc1, 0xc2, 0xb3, 0x5e,
	0xc2, 0x52, 0xc2, 0xeb, 0x85, 0xb6, 0x84, 0x81, 0xf4, 0xb1, 0xa8, 0x2c, 0x8f, 0x82, 0xf4, 0xc7,
	0x92, 0x72, 0x67, 0xc2, 0x58, 0x46, 0xb7, 0xac, 0x30, 0x96, 0x31, 0x57, 0x8f, 0xc7, 0x92, 0x40,
	0xf8, 0x30, 0x96, 0xf4, 0x8b, 0x16, 0xc6, 0x32, 0xe2, 0xbe, 0xc8, 0x13, 0x7b, 0x3f, 0x43, 0xc9,
	0x24, 0x15, 0xfd, 0xb5, 0xe9, 0xd8, 0x2e, 0xd5, 0xf4, 0xab, 0x8a, 0x66, 0x9b, 0x5c, 0xf1, 0xc5,
	0xbd, 0xb6, 0x49, 0x5f, 0x7b, 0x97, 0x15, 0x9d, 0x58, 0xd5, 0x4b, 0x87, 0xe8, 0x9a, 0xe6, 0x54,
	0x23, 0xe0, 0x3d, 0xcd, 0x36, 0xab, 0x6d, 0x52, 0xbd, 0x7e, 0xc0, 0x7f, 0x1f, 0xbe, 0x9c, 0x62,
	0x4d, 0xf1, 0xc1, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x02, 0x1a, 0x49, 0x59, 0x35, 0x16, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FUOTAServerServiceClient is the client API for FUOTAServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FUOTAServerServiceClient interface {
	// CreateDeployment creates the given FUOTA deployment.
	CreateDeployment(ctx context.Context, in *CreateDeploymentRequest, opts ...grpc.CallOption) (*CreateDeploymentResponse, error)
	// CreateMulticastDeployment creates the given Multicast deployment.
	CreateMulticastDeployment(ctx context.Context, in *CreateMulticastDeploymentRequest, opts ...grpc.CallOption) (*CreateMulticastDeploymentResponse, error)
	// CreateMulticastDeployment creates the given Multicast deployment.
	BulkMulticastDeployment(ctx context.Context, in *BulkMulticastDeploymentRequest, opts ...grpc.CallOption) (*BulkMulticastDeploymentResponse, error)
	// GetDeploymentStatus returns the FUOTA deployment status given an ID.
	GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error)
	// GetDeploymentDeviceLogs returns the FUOTA logs given a deployment ID and DevEUI.
	GetDeploymentDeviceLogs(ctx context.Context, in *GetDeploymentDeviceLogsRequest, opts ...grpc.CallOption) (*GetDeploymentDeviceLogsResponse, error)
	// ResetMulticastSetup flushes setup state of the device.
	ResetMulticastSetup(ctx context.Context, in *ResetMulticastSetupRequest, opts ...grpc.CallOption) (*ResetMulticastSetupResponse, error)
}

type fUOTAServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFUOTAServerServiceClient(cc grpc.ClientConnInterface) FUOTAServerServiceClient {
	return &fUOTAServerServiceClient{cc}
}

func (c *fUOTAServerServiceClient) CreateDeployment(ctx context.Context, in *CreateDeploymentRequest, opts ...grpc.CallOption) (*CreateDeploymentResponse, error) {
	out := new(CreateDeploymentResponse)
	err := c.cc.Invoke(ctx, "/fuota.FUOTAServerService/CreateDeployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTAServerServiceClient) CreateMulticastDeployment(ctx context.Context, in *CreateMulticastDeploymentRequest, opts ...grpc.CallOption) (*CreateMulticastDeploymentResponse, error) {
	out := new(CreateMulticastDeploymentResponse)
	err := c.cc.Invoke(ctx, "/fuota.FUOTAServerService/CreateMulticastDeployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTAServerServiceClient) BulkMulticastDeployment(ctx context.Context, in *BulkMulticastDeploymentRequest, opts ...grpc.CallOption) (*BulkMulticastDeploymentResponse, error) {
	out := new(BulkMulticastDeploymentResponse)
	err := c.cc.Invoke(ctx, "/fuota.FUOTAServerService/BulkMulticastDeployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTAServerServiceClient) GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error) {
	out := new(GetDeploymentStatusResponse)
	err := c.cc.Invoke(ctx, "/fuota.FUOTAServerService/GetDeploymentStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTAServerServiceClient) GetDeploymentDeviceLogs(ctx context.Context, in *GetDeploymentDeviceLogsRequest, opts ...grpc.CallOption) (*GetDeploymentDeviceLogsResponse, error) {
	out := new(GetDeploymentDeviceLogsResponse)
	err := c.cc.Invoke(ctx, "/fuota.FUOTAServerService/GetDeploymentDeviceLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTAServerServiceClient) ResetMulticastSetup(ctx context.Context, in *ResetMulticastSetupRequest, opts ...grpc.CallOption) (*ResetMulticastSetupResponse, error) {
	out := new(ResetMulticastSetupResponse)
	err := c.cc.Invoke(ctx, "/fuota.FUOTAServerService/ResetMulticastSetup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FUOTAServerServiceServer is the server API for FUOTAServerService service.
type FUOTAServerServiceServer interface {
	// CreateDeployment creates the given FUOTA deployment.
	CreateDeployment(context.Context, *CreateDeploymentRequest) (*CreateDeploymentResponse, error)
	// CreateMulticastDeployment creates the given Multicast deployment.
	CreateMulticastDeployment(context.Context, *CreateMulticastDeploymentRequest) (*CreateMulticastDeploymentResponse, error)
	// CreateMulticastDeployment creates the given Multicast deployment.
	BulkMulticastDeployment(context.Context, *BulkMulticastDeploymentRequest) (*BulkMulticastDeploymentResponse, error)
	// GetDeploymentStatus returns the FUOTA deployment status given an ID.
	GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error)
	// GetDeploymentDeviceLogs returns the FUOTA logs given a deployment ID and DevEUI.
	GetDeploymentDeviceLogs(context.Context, *GetDeploymentDeviceLogsRequest) (*GetDeploymentDeviceLogsResponse, error)
	// ResetMulticastSetup flushes setup state of the device.
	ResetMulticastSetup(context.Context, *ResetMulticastSetupRequest) (*ResetMulticastSetupResponse, error)
}

// UnimplementedFUOTAServerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFUOTAServerServiceServer struct {
}

func (*UnimplementedFUOTAServerServiceServer) CreateDeployment(ctx context.Context, req *CreateDeploymentRequest) (*CreateDeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeployment not implemented")
}
func (*UnimplementedFUOTAServerServiceServer) CreateMulticastDeployment(ctx context.Context, req *CreateMulticastDeploymentRequest) (*CreateMulticastDeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMulticastDeployment not implemented")
}
func (*UnimplementedFUOTAServerServiceServer) BulkMulticastDeployment(ctx context.Context, req *BulkMulticastDeploymentRequest) (*BulkMulticastDeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkMulticastDeployment not implemented")
}
func (*UnimplementedFUOTAServerServiceServer) GetDeploymentStatus(ctx context.Context, req *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeploymentStatus not implemented")
}
func (*UnimplementedFUOTAServerServiceServer) GetDeploymentDeviceLogs(ctx context.Context, req *GetDeploymentDeviceLogsRequest) (*GetDeploymentDeviceLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeploymentDeviceLogs not implemented")
}
func (*UnimplementedFUOTAServerServiceServer) ResetMulticastSetup(ctx context.Context, req *ResetMulticastSetupRequest) (*ResetMulticastSetupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetMulticastSetup not implemented")
}

func RegisterFUOTAServerServiceServer(s *grpc.Server, srv FUOTAServerServiceServer) {
	s.RegisterService(&_FUOTAServerService_serviceDesc, srv)
}

func _FUOTAServerService_CreateDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTAServerServiceServer).CreateDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuota.FUOTAServerService/CreateDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTAServerServiceServer).CreateDeployment(ctx, req.(*CreateDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTAServerService_CreateMulticastDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMulticastDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTAServerServiceServer).CreateMulticastDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuota.FUOTAServerService/CreateMulticastDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTAServerServiceServer).CreateMulticastDeployment(ctx, req.(*CreateMulticastDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTAServerService_BulkMulticastDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkMulticastDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTAServerServiceServer).BulkMulticastDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuota.FUOTAServerService/BulkMulticastDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTAServerServiceServer).BulkMulticastDeployment(ctx, req.(*BulkMulticastDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTAServerService_GetDeploymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTAServerServiceServer).GetDeploymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuota.FUOTAServerService/GetDeploymentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTAServerServiceServer).GetDeploymentStatus(ctx, req.(*GetDeploymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTAServerService_GetDeploymentDeviceLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentDeviceLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTAServerServiceServer).GetDeploymentDeviceLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuota.FUOTAServerService/GetDeploymentDeviceLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTAServerServiceServer).GetDeploymentDeviceLogs(ctx, req.(*GetDeploymentDeviceLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTAServerService_ResetMulticastSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetMulticastSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTAServerServiceServer).ResetMulticastSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuota.FUOTAServerService/ResetMulticastSetup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTAServerServiceServer).ResetMulticastSetup(ctx, req.(*ResetMulticastSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FUOTAServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fuota.FUOTAServerService",
	HandlerType: (*FUOTAServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeployment",
			Handler:    _FUOTAServerService_CreateDeployment_Handler,
		},
		{
			MethodName: "CreateMulticastDeployment",
			Handler:    _FUOTAServerService_CreateMulticastDeployment_Handler,
		},
		{
			MethodName: "BulkMulticastDeployment",
			Handler:    _FUOTAServerService_BulkMulticastDeployment_Handler,
		},
		{
			MethodName: "GetDeploymentStatus",
			Handler:    _FUOTAServerService_GetDeploymentStatus_Handler,
		},
		{
			MethodName: "GetDeploymentDeviceLogs",
			Handler:    _FUOTAServerService_GetDeploymentDeviceLogs_Handler,
		},
		{
			MethodName: "ResetMulticastSetup",
			Handler:    _FUOTAServerService_ResetMulticastSetup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fuota/fuota.proto",
}
