[package]
name = "chirpstack_api"
description = "ChirpStack Protobuf / gRPC API definitions."
version = "3.0.2"
authors = ["Orne Brocaar <info@brocaar.com>"]
license = "MIT"
homepage = "https://www.chirpstack.io"
repository = "https://github.com/brocaar/chirpstack-api"
edition = "2018"

[dependencies]
protobuf = "2.8.1"
grpc = "0.6.1"
